### ISSUE TITLE
Variables missing from .env.default

### ISSUE THREAD

**Issue by Duncanmoo** [systemseed/drupal_reactjs_boilerplate#1]
I tried out this boilerplate and it is awesome, I am wanting something that makes use of GraphQL for querying data, and only use rest for posts etc. This is a great starting point for me.

The ONLY issue I had is that the variables FRONTEND_HOST are not declared in the .env.default file:
```
FRONTEND_HOST=fe.docker.localhost
BACKEND_HOST=be.docker.localhost
```

Thanks

**Comment by spleshka** [comment]
Hi @Duncanmoo, thank you very much for feeback! Looks like it was missed - fixed :) You'd need to remove `.env` and `reactjs/.env` files from the codebase in order to get those files regenerated on any next `make` command.

Cheers,
Ev.
