### ISSUE TITLE
Remove PLATFORMSH_CLI_TOKEN if it's not needed

### ISSUE THREAD

**Issue by kalabro** [systemseed/drupal_reactjs_boilerplate#11]

**Comment by spleshka** [comment]
@kalabro why do you think it is not needed? It is actually necessary for automatic authentication within P.sh CLI: https://docs.platform.sh/gettingstarted/cli/api-tokens.html. The variable is not used explicitly in CI, but it makes Platform CLI authenticated automatically.

**Comment by spleshka** [comment]
@kalabro I've added a comment explaining this to the circle config file. Let me know if you thing anything else has to be done here, otherwise I'm closing the ticket.
