### ISSUE TITLE
Dirty git status after `make install`

### ISSUE THREAD

**Issue by duozersk** [systemseed/drupal_reactjs_boilerplate#6]
After executing `make install`:

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   drupal/web/sites/default/settings.php

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	drupal/keys/
```

**Comment by kalabro** [comment]
> you expected to add those keys to your repo

Why would you recommend ever commit something secret to git? I thought they should be either generated on the server directly or uploaded in writable mount as any other private file. Please let me know if I'm missing something 🤓

**Comment by duozersk** [comment]
I definitely know fix for the `settings.php` modification - we need to have DB connection array and `hash_salt` value in the main settings.php, then it won't add it there.

As for the `drupal/keys` - I would add this path to .gitignore and may be add some info about them somewhere...

**Comment by spleshka** [comment]
@duozersk @kalabro would you say that `hash_salt` should not be generated upon site install?.. I think it actually should. From the other side, P.sh can use internal variable (https://github.com/systemseed/drupal_reactjs_boilerplate/blob/master/drupal/web/sites/default/settings.platformsh.php#L119), while local value can be set to literally anything. How does it sound to you?

**Comment by spleshka** [comment]
Fixed
