### ISSUE TITLE
Install fails on macOS

### ISSUE THREAD

**Issue by M-Fasciano** [systemseed/drupal_reactjs_boilerplate#66]
-p drupal_reactjs_boilerplate: Installing dependencies for React.js application...
services.php must be a mapping
make[1]: *** [prepare:frontend] Error 15
make: *** [install] Error 2

**Comment by spleshka** [comment]
Hi @M-Fasciano, can you provide the full output, including the command you invoked please?

**Comment by M-Fasciano** [comment]
Hi @spleshka, I'm using `make install` and the full output it's the same as my previous comment.

**Comment by spleshka** [comment]
Thanks for your report @M-Fasciano! We've fixed the issue. Can you clone the repo and try again please?

**Comment by spleshka** [comment]
@M-Fasciano looking at the error message I can assume that you have ddev enabled (maybe partically?) which catches some of the request to .localhost or .docker.localhost. The error message is not related to the code / docker set up from this repository.

**Comment by M-Fasciano** [comment]
@spleshka my bad, I stopped the other project I was working on that was using ddev and now everything seems to work fine. Thank you very much for your help.
