### ISSUE TITLE
Fix broken http protection

### ISSUE THREAD

**Issue by spleshka** [systemseed/drupal_reactjs_boilerplate#8]
After moving out of Drupal to standalone domain, http authentication does not work anymore.

**Comment by kalabro** [comment]
@spleshka could you please provide steps to reproduce? I'd like to take a look.

**Comment by spleshka** [comment]
@kalabro I was just looking at this code https://github.com/systemseed/drupal_reactjs_boilerplate/blob/master/drupal/web/sites/default/http_auth.php#L13 - it bypasses the authentication only if it's internal request. At least this piece of code has to be updated.

**Comment by spleshka** [comment]
Fixed!
